### ISSUE TITLE
Blockshuffle Fails to Start - java.lang.NoSuchMethodError 'void org.bukkit.entity.Player.sendActionBar(java.lang.String)'

### ISSUE THREAD

**Issue by Jinko48** [DevvyDont/BlockShuffle#1]
The following console output is shown immediately after running the /blockshuffle start or tpstart command:

![image](https://user-images.githubusercontent.com/10622872/141605258-797bfbc4-51eb-4a5e-a6e5-a00a5ac5d4c7.png)
Latest log file:
[latest.log](https://github.com/DevvyDont/BlockShuffle/files/7531405/latest.log)

I am running spigot-1.17.1 server to load the plugin.
I'll try to fork and put in a pull request if I can figure this out on my own

.

**Comment by DevvyDont** [comment]
since this is a paper plugin, you need to use paper (fork of spigot) not spigot, theres a little bit of extra functionality that i take advantage of using paper that is not present in spigot 

feel free to download latest version of paper [here](https://papermc.io/downloads) and replace the spigot.jar with it and you should be good to go

**Comment by Jinko48** [comment]
Sweet, that seemed to do the trick. Thanks!
